# Constants for Service Concierge Module

# Booking Statuses
STATUS_PENDING = "PENDING"
STATUS_CONFIRMED = "CONFIRMED"
STATUS_CANCELLED = "CANCELLED"
STATUS_COMPLETED = "COMPLETED"

# WebSocket Event Types
EVENT_SERVICE_RECOMMENDED = "SERVICE_RECOMMENDED"
EVENT_BOOKING_STARTED = "BOOKING_STARTED"
EVENT_LOCATION_SELECTED = "LOCATION_SELECTED"
EVENT_DATE_SELECTED = "DATE_SELECTED"
EVENT_TIME_SELECTED = "TIME_SELECTED"
EVENT_BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
EVENT_BOOKING_CANCELLED = "BOOKING_CANCELLED"
EVENT_CALL_STARTED = "CALL_STARTED"
EVENT_CALL_ENDED = "CALL_ENDED"

# Decision Severities
SEVERITY_SAFE = "SAFE"
SEVERITY_WARNING = "WARNING"
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_EMERGENCY = "EMERGENCY"
